### ISSUE TITLE
ImportError: cannot import name 'DefaultParamsReadable'

### ISSUE THREAD

**Issue by githubhnw** [b96705008/custom-spark-pipeline#1]
Hello, 

I'm using Spark 2.2 and tested also on Spark 2.3.0. and I get this error when importing DefaultParamsReadable and DefaultParamsWritable:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-51-3a1281943ff4> in <module>()
----> 1 from pyspark.ml.util import JavaMLReadable, JavaMLWritable, DefaultParamsReadable, DefaultParamsWritable

ImportError: cannot import name 'DefaultParamsReadable'

**Comment by b96705008** [comment]
Hi, DefaultParamsReadable and DefaultParamsWritable are availiable since Spark 2.3.
Therefore, you can not use it in Spark 2.2.
I have a branch, called spark_2.1, and you may try it in spark 2.2.
However, DefaultParamsReadable and DefaultParamsWritable are keys to serialize custom models.
If you want that function, you probably should switch to spark 2.3.

**Comment by githubhnw** [comment]
Hello, I tried also with Spark 2.3.0, see below: 

![image](https://user-images.githubusercontent.com/24211109/44028834-e075b706-9f03-11e8-911f-b3b15449900e.png)
 

So...still cannot import DefaultParamsReadable/Writable.

**Comment by b96705008** [comment]
You can check start-notebook.sh, especially PYTHONPATH.
```
#!/bin/sh
export SERVICE_HOME="$(cd "`dirname "$0"`"; pwd)"
export PYTHONPATH=${PYTHONPATH}:/${SERVICE_HOME}/app
export PYSPARK_DRIVER_PYTHON=jupyter
export PYSPARK_DRIVER_PYTHON_OPTS="notebook --port 8080"

pyspark \
	--name Jupyter_Spark \
	--master local[*]
```

Did you start your app by input below method?
```
./start-notebook.sh
```

**Comment by githubhnw** [comment]
Hello, I figured it out and now works. Thanks, Raluca

**Comment by b96705008** [comment]
Great!
